$kind: http-request
name: Update Role
method: PUT
url: '{{base_url}}/api/v1/roles/{{role_id}}'
order: 4000
headers:
  Content-Type: application/json
  Accept: application/json
body:
  type: json
  content: |-
    {
      "name": "Senior Manager",
      "permissions": ["read", "write", "delete"]
    }
